#! /bin/sh
#
# List all plots for $network.
#
# These are only basenames, without the .eps suffix
#
# Only existing files are output. 
#

{
	
	for x in ax ux vx uv ; do
		echo bidd."$x"."$network"
	done
	for x in a u v ; do
		echo degree."$x"."$network"
	done
	for x in a u v ; do
		echo assortativity."$x"."$network"
	done
	for x in a u v ; do
		echo lorenz."$x"."$network"
	done
	for x in b c d ; do
		echo weights."$x"."$network"
	done
	echo time_histogram."$network"
	echo time_histogram_signed."$network"
	echo diadens."$network"
	echo cluscod."$network"
	for x in a b c d e f g ; do
		echo hopdistr."$x"."$network"
	done
	for x in a b c ; do
		echo hopdistr_time.full."$x"."$network"
	done
	for x in a b c ; do
		echo outin."$x"."$network"
	done
	
} | while IFS= read -r name ; do
	[ -e plot/"$name".eps ] && {
		size=$(stat -c%s plot/"$name".eps)
		[ "$size" -gt 4096 ] && printf '%s\n' "$name"
	}
done

exit 0
