#! /bin/sh
# 
# Some plots exist as files but we don't show them because they contain
# errors--they are too small, and it is likely than Matlab crashed while
# producing them. 
#
# INVOCATION
#	$1	filename without suffix
#

filename="$1"

[ "$filename" ] || exit 2

if [ -e "$filename".eps ] ; then
	size=$(stat -c%s "$filename".eps)
	if [ "$size" -gt 4096 ] ; then
		exit 0
	else
		exit 1
	fi
elif [ -e "$filename".png ] ; then
	size=$(stat -c%s "$filename".png)
	if [ "$size" -gt 0 ] ; then
		exit 0
	else
		exit 1
	fi
else
	exit 1
fi
