#! /bin/sh
#
# INPUT FILES 
#	dat/PLOTS
#

set -e

cat <<EOF
#nav:<A HREF="../">KONECT</A> ‣
<H1>Plots</H1>
<P>A plot is a figure that visualizes a certain aspect of a network. 
</P>
<UL>
EOF
for plot in $(cat dat/PLOTS) ; do
	cat <<EOF
<LI><A HREF="$plot/">$plot</A>
EOF
done
cat <<EOF
</UL>
EOF
