#! /bin/sh
#
# Write the given references in HTML.  All references must appear in the
# file 'konect-extr/konect.bib'.
#
# PARAMETERS
# 	$1	List of Bibtex keys, separated by commas and/or spaces
#
# STDOUT
#	The HTML text of the references 
#

cite=$1

[ "$cite" ] || {
	echo >&2 "*** Expected \$cite to contain the Bibtex keys"
	exit 1
}

# Make sure they all exist, because Bibtex2Html does *not*
# return a non-zero exit status when references are missing. 
for bibkey in $(echo "$cite" | tr ',' ' ') ; do
	grep -q -E '\{\s*'"$bibkey"'\s*,\s*$' konect-extr/konect.bib || {
		echo >&2 "*** Bibtex reference '$bibkey' used by network '$network' expected in 'konect-extr/konect.bib', but not found"
		exit 1
	}
done
	
tmpfile=$(mktemp)
{ printf '%s\n' "$cite" | sed -E -e 's|,|\
|g' ; } >"$tmpfile"
dir=$(pwd)
cd "$(dirname "$tmpfile")"
tmpfile2=$(mktemp)
bibtex2html -q -w --citefile "$(basename "$tmpfile")" --nodoc --nobibsource -o - --no-header "$dir"/konect-extr/konect.bib >"$tmpfile2" || {
	echo >&2 "*** Error running bibtex2html"
	echo >&2 "Content of citefile '$tmpfile':"
	cat >&2 -- "$tmpfile"
	exit 1
}
exitstatus=$?
<"$tmpfile2" sed -E -e 's,<hr>.*$,,;tx;by;:x;q;:y' | sed -E -e 's,--,–,g'
rm -f -- "$tmpfile" "$tmpfile2"
