#! /bin/sh
#
# Generate skeleton of the "plots" page. 
#
# STDOUT
#	Skeleton of page 
#
# INPUT FILES 
#	skeleton/plots/table.html
#

set -e

cat <<EOF
#nav:<A href="${root}/">KONECT</A> ‣
<H1>Plots</H1>
<P>A <B>plot</B> is a figure that visualizes a certain aspect of a network. 
</P>
EOF

cat skeleton/plots/table.html
