#! /bin/sh
# -*-html-*-

cat <<EOF
#nav:<A href="${root}/networks/">Networks</A> • <A href="${root}/statistics/">Statistics</A> • <A href="${root}/plots/">Plots</A> • <A href="${root}/categories/">Categories</A> • <A href="https://github.com/kunegis/konect-handbook/raw/master/konect-handbook.pdf">Handbook</A>

<H1>The KONECT Project</H1>

<P style="text-align:center;">Jérôme Kunegis <BR><SPAN style="font-size:85%;">University of Namur</SPAN></P>

<P>
  This is the KONECT project, a project in the area of <EM>network
  science</EM> with the goal to collect network datasets,
  analyse them, and make available all analyses online.
  <I>KONECT</I> stands
  for <I><U>Ko</U>blenz <U>Ne</U>twork <U>C</U>ollec<U>t</U>ion</I>, as
  the project has roots at the University of Koblenz–Landau in Germany.
  All source code is made available as Free Software, and includes a
  network analysis toolbox for GNU Octave, a network extraction library,
  as well as code to generate these web pages, including all statistics
  and plots.  KONECT is run by the research group
  around <A href="https://directory.unamur.be/staff/jkunegis?_LOCALE_=en">Jérôme
  Kunegis</A> at the <A href="https://www.unamur.be/en">University of
  Namur</A>, in the <A href="http://www.naxys.be/">Namur Center for
  Complex Networks</A>.
</P>
<P>
  The KONECT project has
  <B>$(<dat/NETWORKS wc -l | sh/format-int)</B> network datasets
  in <B>$(<dat/CATEGORIES wc -l | sh/format-int)</B> categories. 
  We have computed <B>$(<dat-www/COUNT_STATISTICS sh/format-int)</B> graph statistics
  and generated <B>$(<dat-www/COUNT_PLOTS sh/format-int)</B> plots. 
</P>
<P>
  For a general overview, see
  the <A href="https://github.com/kunegis/konect-handbook/raw/master/konect-handbook.pdf">KONECT
  Handbook</A>. 
  For news, <A href="https://twitter.com/KONECTproject">follow @KONECTproject on Twitter</A>. 
</P>

<H2>Browse</H2>
<UL>
  <LI><B><A href="networks/">Networks</A></B>:  <A href="networks/ucidata-zachary/">Karate club</A> • <A href="networks/slashdot-zoo/">Slashdot Zoo</A> • <A href="networks/twitter/">Twitter followers</A> • <A href="networks/">more…</A>
  <LI><B><A href="statistics/">Statistics</A></B>:  <A href="statistics/clusco/">Clustering coefficient</A> • <A href="statistics/diam/">Diameter</A> • <A href="statistics/alcon/">Algebraic connectivity</A> • <A href="statistics/">more…</A>
  <LI><B><A href="plots/">Plots</A></B>:  <A href="plots/degree/">Degree distribution</A> • <A href="plots/assortativity/">Degree assortativity plot</A> • <A href="plots/hopdistr/">Hop plot</A> • <A href="plots/">more…</A>
  <LI><B><A href="categories/">Categories</A></B>:  <A href="categories/Social/">Online social networks</A> • <A href="categories/Citation/">Citation networks</A> • <A href="categories/Hyperlink/">Hyperlink networks</A>  • <A href="categories/">more…</A> 
</UL>

<H2>Source code</H2>
<P>
  The sources of KONECT are available as free software, under the GNU
  General Public License (GPL) version 3.  They are hosted on GitHub. 
</P>
<UL>
  <LI><A href="https://github.com/kunegis/konect-www">Website</A> – Code for generating this website
  <LI><A href="https://github.com/kunegis/konect-extr">Extraction</A> – Code for generating the networks
  <LI><A href="https://github.com/kunegis/konect-analysis">Analysis</A> – Code for computating all statistics and plots
  <LI><A href="https://github.com/kunegis/konect-toolbox">Toolbox</A> – Octave toolbox for network analysis
  <LI><A href="https://github.com/kunegis/konect-handbook">Handbook</A> – The KONECT Handbook
</UL>
EOF
