#! /bin/sh
#
# Write the page about one statistic. 
#
# PARAMETERS
#	$statistic
#
# INPUT FILES
#	dat/NETWORKS
#

cat <<EOF
<A HREF="../../">KONECT</A> ‣ <A HREF="../">Statistics</A> ‣
<H1>$statistic</H1>
<P>These are the values of the statistic '$statistic' for all networks.
</P>
<TABLE>
EOF
for network in $(cat dat/NETWORKS) ; do
##for file in dat/statistic."$statistic".* ; do
##	network=$(printf '%s' "$file" | sed -E -e 's,^.*\.([^.]+)$,\1,')
	export network
	filename=dat/statistic."$statistic"."$network"
	[ -e "$filename" ] || continue
	value=$(head -1 "$filename")
	cat <<EOF
<TR><TD><A HREF="../../networks/$network">$(field=name sh/read-meta)</A>	<TD>$value
EOF
done
cat <<EOF
</TABLE>
EOF
