#! /bin/sh
#
# Write the skeleton of the webpage for one network. 
#
# PARAMETERS
#	$network
#
# STDOUT
#	Content is written here
#
# INPUT FILES
#	dat/STATISTICS
#	dat-www/plots-network.$network 
#

set -e

meta_name=$(field=name sh/read-meta)

cat <<EOF
<A HREF="../../">KONECT</A> &gt; <A HREF="../">Networks</A> &gt;
<H1>$meta_name</H1>
<P>
$(field=long-description sh/read-meta | recode utf8..html)
</P>

<H2>Metadata</H2>
<TABLE>
<TR><TD>Name          <TD>$meta_name
<TR><TD>Code          <TD><CODE>$(field=code sh/read-meta)</CODE>
<TR><TD>Internal name <TD><CODE>$network</CODE>
<TR><TD>Category      <TD>$(field=category sh/read-meta)
</TABLE>

<H2>Statistics</H2>
<TABLE>
EOF

while IFS= read -r statistic
do
	if [ -e dat/statistic."$statistic"."$network" ] ; then
		value=$(<dat/statistic."$statistic"."$network" head -1)
		echo "<TR><TD>$statistic</TD><TD>$value</TD></TR>"
	fi
done <dat/STATISTICS

cat <<EOF
</TABLE>

<H2>Plots</H2>
EOF

for file in $(cat dat-www/plots-network."$network")
do
	echo "<A HREF=\"../../plot/$file.full.png\"><IMG SRC=\"../../plot/$file.small.png\"></A>"
done
