#! /bin/sh
#
# Generate the full HTML page from a skeleton.
#
# PARAMETERS
#	$name
#
# INPUT FILES
#	skeleton/$name.html
#	static/(head foot).html
#
# STDOUT
#	The HTML (all ASCII) 
#

set -e 

title=$(<skeleton/"$name".html sed -E -e 's|^.*<H1>(.*)</H1>.*$|\1|;t;d')

if [ -z "$title" ] ; then
	echo >&2 "*** Expected a title, but found none"
	exit 1
fi

mkdir -p "$(dirname www/"$name".html)"
{
	title_escape=$(printf '%s' "$title" | sed -E -e 's|,|\\,|g')
	<static/head.html sed -E -e 's,\$\{title\},'"$title_escape"','
	echo
	cat skeleton/"$name".html
	echo 
	cat static/foot.html
}
