#! /bin/sh
#
# Write content of 'networks/index.html'.
#
# STDOUT
#	Content
# 
# INPUT FILES
#	dat/NETWORKS	List of all networks
#

set -e

[ -e dat/NETWORKS ]
count=$(echo $(<dat/NETWORKS wc -l))

cat <<EOF
<A HREF="../">KONECT</A> &gt;
<H1>Networks</H1>
<P>KONECT has $count networks.</P>
<UL>
EOF
while IFS= read -r network ; do
	echo "<LI><A href=\"$network/\">$network</A>"
done <dat/NETWORKS
echo "</UL>"
