#! /bin/sh
#
# Write the page about one statistic. 
#
# PARAMETERS
#	$statistic
#
# INPUT FILES
#	skeleton/statistics/$statistic/table.html
#	dat-www/html-symbol.$statistic
#

symbol=$(cat dat-www/html-symbol."$statistic")
name=$(sh/name-statistic)
name_lc=$(printf '%s' "$name" | sed -E -e 'h;s,^(.).*$,\1,;y,ABCDEFGHIJKLMNOPQRSTUVWXYZ,abcdefghijklmnopqrstuvwxyz,;G;s,\
.,,')

cat <<EOF
#nav:<A HREF="../../">KONECT</A> ‣ <A HREF="../">Statistics</A> ‣
<H1>$name</H1>
<P>These are the values of the <B>$name_lc</B> ($symbol) for all networks.
</P>
EOF

cat skeleton/statistics/"$statistic"/table.html
