#! /bin/sh
#
# Write content of 'networks/index.html'.
#
# STDOUT
#	Content
# 
# INPUT FILES
#	dat/NETWORKS	
#	skeleton/networks/table.html
#

set -e

[ -e dat/NETWORKS ]
count=$(echo $(<dat/NETWORKS wc -l))

cat <<EOF
#nav:<A href="${root}/">KONECT</A> ‣
<H1>Networks</H1>
<P>KONECT has <B>$count networks</B>.</P>
EOF
cat skeleton/networks/table.html
