#! /bin/sh
#
# Generate the "categories" page.
#
# STDOUT
#	The skeleton of the page
#
# INPUT FILES
#	skeleton/categories/table.html
#

set -e

cat <<EOF
#nav:<A href="${root}/">KONECT</A> ‣
<H1>Categories</H1>
<P>
  In KONECT, each belongs to a <B>category</B> which denotes the
  semantics of the network.  Examples of categories are social networks,
  road networks, and citation networks. 
</P>
EOF

cat skeleton/categories/table.html
